### ISSUE TITLE
Display of 64-bit CSRs in MC-1 (RV32) is confusing

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#174] opened 2024-10-23 21:47 UTC
Here's a good example. The cycle CSR is defined as 64-bit which is fine but it isn't made clear that reading from 0xc00 returns the least-significant 32 bits. Also, the cycleh CSR is defined as 32-bit which is inconsistent with the cycle CSR and doesn't make clear the most-significant 32 bits are read by cycleh. 

There is the concept of the CSR size and then their is the concept of which bits of that CSR are accessed by a particular CSR address. These concepts are somewhat mixed which is creating the confusion/inconsistency.

![image](https://github.com/user-attachments/assets/4c682f69-0719-46fe-86b0-d604c4a70968)

![image](https://github.com/user-attachments/assets/efbea7b5-df53-4704-ac1d-d4ea5c22e96c)

**Comment by dhower-qc** [comment] 2024-10-25 16:54
duplicate of #108

**Closed by dhower-qc** 2024-10-25 16:54 UTC
Labels: enhancement
