### ISSUE TITLE
Bleeding through of Asciidoc in HPM CSRs and typo ("mhpmconuter30")

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#117] opened 2024-10-17 16:02 UTC
![image](https://github.com/user-attachments/assets/cf6e73e8-78c5-417d-9814-93f2fbbc298f)

**Comment by dhower-qc** [comment] 2024-10-17 18:37
The bleeding is a duplicate of #63

**Closed** 2024-10-17 19:35 UTC
